---
title: "Evaluation"
---

Insert filled in text from intro-script-template here.


#Part 1: Setup

Download RStudio if possible. Open a new session.  At the end of this evaluation, you will be asked to create and send me an .Rhistory file containing a history of everything you've typed during this session. Instructions for this will be given at the end of this document.

#Part 2: Making a Template

Provide data set and instruct them to make a templat which (I know) is an appropriate length to match some patterns in the data.

#Part 3: Window Length and Matching Threshold

Provide a different data set that will not match the pattern unless they adjust the window length. Give them a hint as to what caused the pattern, and what length it should be or something like that.

Have them adjust the spearmans rho threshold until they are satisfied that the patterns returned are good patterns

#Part 4: Distinctive Feature

Provide a dataset (and pattern template) where the pattern has much higher values than the dataset, ask users to try and think of and implement a distinctive feature that will decrease the run time of this query.

#Part 5: Ruleset

Provide a dataset with lots of patterns, and ask users to use the rulset parameter to make it return only the ones that have some particular quality about them.

#Part 6: Questionnaire 

The command below will save everything you have typed during this session into a file called "evaluation.Rhistory". It will then print the contents of that file to your console. Please copy and paste this command into the R console and run it. Then copy and paste the output into the Google form before. Once you have done this, please answer the rest of the questions on the form.

```{r, fig.show='hold', eval=FALSE}
savehistory("evaluation.Rhistory")  
scan('evaluation.Rhistory','character', sep = "\n"). 
```


Google form goes here

#Part 7: Debriefing

Insert filled in text from debrief-script-template here
